POST http://localhost:5218/api/Todos/Create
Content-Type: application/json

{
  "work": "Deneme",
  "deadLine": "2024-08-10"
}

###

GET http://localhost:5218/api/Todos/GetAll
Accept: application/json

###

DELETE http://localhost:5218/api/Todos/DeleteById?id=34cb8e4e-9003-47e0-9bbf-00024b1b4891


###

GET http://localhost:5218/seed-data